version: 2.1

jobs:
  lsif-node:
    docker:
      - image: sourcegraph/lsif-go@sha256:14ecaa6c0dff7988783ac5d8bd7d02be9bc648addc2074a47657a33597492583
    steps:
      - checkout
      - run: lsif-go
      - run: src lsif upload -no-progress

workflows:
  lsif-node:
    jobs:
      - lsif-node
